pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'NeoForged'
            url = 'https://maven.neoforged.net/releases'
            content {
                includeGroupAndSubgroups 'net.neoforged'
            }
        }
        gradlePluginPortal()
    }

    plugins {
        id 'fabric-loom' version loom_version
        id 'net.neoforged.moddev' version moddev_version
    }

}

rootProject.name = 'mcef'

include 'neoforge'
